---
file-stores:
  s1:
    source:
      csv:
        index-file: sources/csv/index.csv
        id-column: id
        filename-column: filename
        filename-suffix: .txt
        root-path: sources/csv
    cache:
      path: ./cache/{store}
    on-get:
      run: cat "{file}"
